### ISSUE TITLE
libtool eval not work and i get ang >:(

### ISSUE THREAD

**Issue by Nasanian** [kalmari246/moo#14]
../libtool: eval: line 1723: syntax error near unexpected token `|'
../libtool: eval: line 1723: `x86_64-pc-linux-musl-nm  .libs/channel.o .libs/comp.o .libs/crypt.o .libs/hostkey.o .libs/kex.o .libs/mac.o .libs/misc.o .libs/packet.o .libs/publickey.o .libs/scp.o .libs/session.o .libs/sftp.o .libs/userauth
.o .libs/transport.o .libs/version.o .libs/knownhost.o .libs/agent.o .libs/openssl.o .libs/pem.o .libs/keepalive.o .libs/global.o .libs/blowfish.o .libs/bcrypt_pbkdf.o   |  | /usr/bin/sed 's/.* //' | sort | uniq > .libs/libssh2.exp'
make[2]: *** [Makefile:547: libssh2.la] Error 2
make[2]: Leaving directory '/var/tmp/paludis/build/net-libs-libssh2-1.9.0/work/libssh2-1.9.0/src'
make[1]: *** [Makefile:461: all] Error 2
make[1]: Leaving directory '/var/tmp/paludis/build/net-libs-libssh2-1.9.0/work/libssh2-1.9.0/src'
make: *** [Makefile:546: all-recursive] Error 1

!!! ERROR in net-libs/libssh2-1.9.0::arbor:
!!! In /usr/x86_64-pc-linux-musl/libexec/paludis/utils/exheres-0/emake at line 30
!!! emake returned error 2

!!! Call stack:
!!!    * paludis_die_or_error_func (/usr/x86_64-pc-linux-musl/libexec/paludis/die_functions.bash:82)
!!!    * main (/usr/x86_64-pc-linux-musl/libexec/paludis/utils/exheres-0/emake:30)

ok internal scream begin

**Comment by kalmari246** [comment]
cant reproduce

**Comment by kalmari246** [comment]
![unknown](https://user-images.githubusercontent.com/50865020/92994054-890cc080-f529-11ea-82be-9087596b3a98.png)

**Comment by Nasanian** [comment]
gae
