### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by kalmari246** [kalmari246/moo#2]
- [x] dont use --ignore-*
- [x] cross glibc or something fails (stdio.h missing)
- [x] why does this exist
- [x] fix @ intex @ uni
- [x] learn how to use exherbo
- [x] stop using gentoo
- [x] question life
- [x] why does exherbo use systemdeez nutts

**Comment by kalmari246** [comment]
no, im eating my toasted sandwich

**Comment by Nasanian** [comment]
speed

**Comment by kalmari246** [comment]
ok i just realised hashtags in commits reference issues
